name: Fetch and Update Timetables

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest 

      - name: Install dependencies
        run: bun install node-fetch adm-zip

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs

      - name: Run script to fetch timetables
        run: bun run ./scripts/get-timetables.ts

      - name: List contents of data directory
        run: |
          echo "Listing contents of ./data/ directory:"
          ls -R ./data
          echo "Finished listing ./data/ directory."

      - name: Commit and push updated data
        run: |
          git lfs install --skip-smudge # Initialize LFS for the runner
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p data
          # Track the large file(s) with LFS. This creates/updates .gitattributes
          git lfs track "data/stop_times.txt"
          # Add .gitattributes to ensure LFS configuration is committed
          git add .gitattributes
          git add data
          if git diff --staged --quiet data && git diff --staged --quiet .gitattributes; then
            echo "Timetables data is up to date."
          else
            git commit -m "Update timetables data (using LFS for large files)"
            git push
          fi
