name: Fetch and Update Timetables

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3 AM UTC

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest 

      - name: Install dependencies
        run: bun install node-fetch adm-zip

      - name: Run script to fetch timetables
        run: bun run ./scripts/get-timetables.ts

      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p data
          git add data
          if git diff --staged --quiet data; then
            echo "Timetables data is up to date."
          else
            git commit -m "Update timetables data"
            git push
          fi
